name: Test con Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2

      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        start: npm run test     